### PR TITLE
Migration SignatureDataConversion to .NET Core

### LINKED ISSUE #113: SignatureDataConversion_dotNet cause wrong assembly information on ASP.NET Core projects.
Hi @brinley,

**SignatureDataConversion_dotNet** can cause [wrong assembly information on ASP.NET Core projects, dotnet/cli #3620](https://github.com/dotnet/cli/issues/3620).

This is because SignatureDataConversion_dotNet project contains `AssemblyInfo.cs` and when I add jSignature to my project (via Bower) then by default Visual Studio treat this file like as part of my project...

By default ASP.NET Core projects don't include `AssemblyInfo.cs` and necessary meta data are taken from `project.json`.

So, when I add jSignature to my project (via Bower) then `AssemblyInfo.cs` file form jSignature is in use by Visual Studio.

Of course there is solution for this, but still it can make confusion for developers who don't know about that

Will be great if we can sort this on jSignature level ?

My suggestions how to deal with `SignatureDataConversion_dotNet`:

 - archive this project and store it as ZIP file (all extras can be stored as ZIP),
 - remove it form jSignature bower package (looks like old project), and put it as external download,
 - upgrade project to VS2015 / .NET Core without `AssemblyInfo.cs` (currently it's VS2008 / .NET Framework 2.0 project).

What do you thing about that ?

### PR DESCRIPTION
**Pull request by LukaszDev**
Migration SignatureDataConversion_dotNet project to .NET Core / Visual Studio 2015.

This closes #113

### CODE REVIEW

**Comment by LukaszDev** [comment]
Hi @Brinley,

I have prepared new Pull Request with correct version like you ask, and also updated references to latest version of .NET Core and NUnit.

**Comment by LukaszDev** [comment]
And sorry for this last commit - I forgot few important files ;)

Please merge all those commits into one :)

**Comment by brinley** [comment]
Sorry I forgot to response but you were right about this possibly a breaking check so we should update the major version number instead. I also noticed you updated the tests, have you executed them and they pass?

**Comment by LukaszDev** [comment]
Ok, version is updated now to v2.

Yes, all tests pass:

tests

**Comment by brinley** [comment]
Thanks @LukaszDev

**Pull request merged**
